import Head from 'next/head'
import { Header } from '@/components/Header'
import { ProductsCard } from '@/components/ProductsCard'
import { Footer } from '@/components/Footer'
import { GlobalStyles } from '@/styles/global'

export default function Home() {
  return (
    <>
      <GlobalStyles />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Header />
        <ProductsCard />
        <Footer />
      </main>
    </>
  )
}
